"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import useSWR from "swr";
import type { DuaCategory,DuaEntry,DuaSummary } from "@/lib/dua";
import { hasLocalBookmark,readLocalBookmarks,toggleLocalBookmark } from "@/lib/local-bookmarks";
import styles from "./feature-pages.module.css";
const fetcher=(url:string)=>fetch(url).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d});
const icons:Record<string,string>={"morning-dhikr":"☀","evening-dhikr":"☾","daily-dua":"✦","selected-dua":"❖","dhikr-after-salah":"◈"};

export function DuaCategories(){const{data,error,isLoading}=useSWR<{items:DuaCategory[]}>("/api/dua/categories",fetcher);return <main className={styles.page}><header className={styles.pageHeader}><div><span className={styles.eyebrow}>Hisnul Muslim</span><h1>Dua</h1><p>Authentic daily duas and dhikr, kept with their Arabic, meaning, and source reference.</p></div></header>{isLoading?<p>Loading categories…</p>:null}{error?<p className={styles.errorText}>Dua content is unavailable right now. No substitute content has been used.</p>:null}<section className={styles.categoryGrid}>{data?.items.map(item=><Link className={styles.categoryCard} href={`/dua/${item.slug}`} key={item.slug}><span className={styles.categoryIcon}>{icons[item.slug]??"✦"}</span><div><h2>{item.name}</h2><p>{item.total} entries</p></div><b>→</b></Link>)}</section><p className={styles.sourceNote}>Source: fitrahive/dua-dhikr (MIT). Categories reflect the source’s current English catalog.</p></main>}

export function DuaCategoryList({slug}:{slug:string}){const{data,error,isLoading}=useSWR<{items:DuaSummary[]}>(`/api/dua/categories/${slug}`,fetcher);const[query,setQuery]=useState("");const items=useMemo(()=>data?.items.filter(item=>item.title.toLowerCase().includes(query.toLowerCase()))??[],[data,query]);return <main className={styles.page}><Link className={styles.backLink} href="/dua">← All Dua categories</Link><header className={styles.pageHeader}><div><span className={styles.eyebrow}>Dua collection</span><h1>{data?.items[0]?.categoryName??"Dua"}</h1><p>Open an entry to read its Arabic, transliteration, translation, and source.</p></div></header><label className={styles.searchBox}><input type="search" placeholder="Search this category" value={query} onChange={e=>setQuery(e.target.value)}/></label>{isLoading?<p>Loading duas…</p>:null}{error?<p className={styles.errorText}>This category is unavailable right now.</p>:null}<section className={styles.duaList}>{items.map((item,index)=><Link className={styles.duaCard} href={`/dua/${slug}/${item.id}`} key={item.id}><div className={styles.duaHead}><h2>{index+1}. {item.title}</h2><b>→</b></div></Link>)}</section></main>}

export function DuaDetail({slug,id}:{slug:string;id:string}){const{data,error,isLoading}=useSWR<{item:DuaEntry}>(`/api/dua/categories/${slug}/${id}`,fetcher);const[bookmarks,setBookmarks]=useState(readLocalBookmarks);useEffect(()=>setBookmarks(readLocalBookmarks()),[]);const item=data?.item;const bookmarkId=`dua:${slug}:${id}`;return <main className={styles.page}><Link className={styles.backLink} href={`/dua/${slug}`}>← Back to category</Link>{isLoading?<p>Loading dua…</p>:null}{error?<p className={styles.errorText}>This dua is unavailable right now. No substitute content has been used.</p>:null}{item?<article className={styles.duaCard}><div className={styles.duaHead}><div><span className={styles.eyebrow}>{item.categoryName} · {item.id}</span><h1>{item.title}</h1></div><button className={styles.bookmark} onClick={()=>setBookmarks(toggleLocalBookmark({id:bookmarkId,label:item.title,reference:item.source,type:"dua",url:`/dua/${slug}/${id}`}))}>{hasLocalBookmark(bookmarks,bookmarkId)?"Saved":"Bookmark"}</button></div><p className={styles.duaArabic} lang="ar" dir="rtl" translate="no">{item.arabic}</p><p className={styles.transliteration}>{item.latin}</p><p className={styles.translation} translate="no">{item.translation}</p>{item.notes?<p><strong>Practice:</strong> {item.notes}</p>:null}{item.fawaid?<p><strong>Benefit noted by source:</strong> {item.fawaid}</p>:null}<p className={styles.reference}>Source reference: {item.source||"Reference unavailable"}</p></article>:null}</main>}
